SUBS = src
SHELL = /bin/sh

it install depend clean:
	@-X=`pwd`; \
	for i in $(SUBS); \
	do echo '<<<' $$i '>>>'; cd $$X/$$i; \
	make $@ PROJDIR=$(@D); done
##	make $@ PROJDIR=$(ESPS_BASE)/../src/ESPS/general/src/lib_header/sphere2.6 ; done \
## SDI 18 Aug 2006 Removed reference to ESPS_BASE so that source tree can \
## be separate from installation \
#
#bare: clean
#	rm -f bin/* lib/packages/*.pas lib/lib*.a 
