#!/bin/sh
# 
#  This material contains proprietary software of Entropic Speech, Inc.   
#  Any reproduction, distribution, or publication without the prior	   
#  written permission of Entropic Speech, Inc. is strictly prohibited.
#  Any public distribution of copies of this work authorized in writing by
#  Entropic Speech, Inc. must bear the notice			
# 								
#      "Copyright (c) 1987 Entropic Speech, Inc.; All rights reserved"
# 				
#  Test script for range.
#  @(#)testfile	3.1  10/20/87  ESI
#
echo "Testing range."
USE_ESPS_COMMON=""
export USE_ESPS_COMMON
ESPS_VERBOSE=0
export ESPS_VERBOSE
ESPSCOM=./common
export ESPSCOM
testsd -f200 -p80 - | plotsd -
range
cat common
