.\" Copyright (c) 1996 Entropic Research Laboratory, Inc.; All rights reserved
.\" @(#)play.1	1.6 11/21/96 ERL
.ds ]W (c) 1992 Entropic Research Laboratory, Inc.
.TH  PLAY 1\-ESPS 11/21/96
.SH NAME
play -\ see splay, s16play, sgplay, hpplay, decplay, lplay
.SH DESCRIPTION
.PP
Currently ESPS supports these systems for audio output.  See the man
page for each play program for details. 
.PP
\fIsplay\fR - \tsend ESPS sampled data to the SPARCstation 8 bit codec output.
.PP
\fIs16play\fR - \tsend sampled data to Sun Sparc 16 bit dbri audio port.
.PP
\fIsgplay\fR - \tsend sampled data to Indigo D/A converter.
.PP
\fIhpplay\fR - \tsend sampled data to HP 700/C100 audio.
.PP
\fIdecplay\fR - \tsend sampled data to DEC Alpha audio.
.PP
\fIlplay\fR - \tsend sampled data to linux audio.
.PP
.SH "SEE ALSO"
\fIrecord\fR (1-ESPS), \fIplaytest\fR (1-ESPS),
\fIrandplay\fR (1-ESPS), \fIsdcomp\fR (1-ESPS).
.PP
.SH AUTHOR
.PP
Derek Lin
