.\" Copyright (c) 1996 Entropic Research Laboratory, Inc.; All rights reserved
.\" @(#)record.1	1.7 11/21/96 ERL
.ds ]W (c) 1992 Entropic Research Laboratory, Inc.
.TH  RECORD 1\-ESPS 11/21/96
.SH NAME
record -\ see srecord, s16record, sgrecord, hprecord, decrecord, lrecord
.SH DESCRIPTION
.PP
Currently ESPS supports these systems for audio input.  See the man page for 
each record program for details.
.PP
\fIsrecord\fR - \tmono record to disk or pipe from SPARCstation 8 bit codec input.
.PP
\fIs16record\fR - \tmono or stereo record to disk or pipe for 16 bit Sparc dbri 
A/D converter.
.PP
\fIsgrecord\fR - \tmono or stereo record to disk or pipe for SGI Indigo A/D converter.
.PP
\fIhprecord\fR - \tmono or stereo record to disk or pipe for HP 700/C100.
.PP
\fIdecrecord\fR - \tmono or stereo record to disk or pipe for DEC Alpha audio.
.PP
\fIlrecord\fR - \tmono or stereo record to disk or pipe for linux audio.
.SH "SEE ALSO"
\fIplay\fR (1-ESPS)
.PP
.SH AUTHOR
.PP
Derek Lin
