#! /bin/sh
# @(#)testfile	1.1 3/9/90 ESI
# test file for mu2esps

testsd -a- -i a.sd << EOD
0 
187 
359 
455 
495 
455 
359 
187 
0 
-187 
-359 
-455 
-495 
-455 
-359 
-187 
0 
187 
359 
455 
495 
455 
359 
187 
0 
-187 
-359 
-455 
-495 
-455 
-359 
-187 
EOD

echo There should be no diff output for the following:
echo " "
echo "cat a.mu | mu2esps - - | pspsdiff -H - a.sd"
cat a.mu | mu2esps - - | pspsdiff -H - a.sd
cat a.mu | mu2esps - - | pspsdiff -H - a.sd
