#  This material contains proprietary software of Entropic Speech, Inc.   
#  Any reproduction, distribution, or publication without the the prior	   
#  written permission of Entropic Speech, Inc. is strictly prohibited.
#  Any public distribution of copies of this work authorized in writing by
#  Entropic Speech, Inc. must bear the notice			
# 								
#      "Copyright (c) 1987 Entropic Speech, Inc.; All rights reserved"
# 				
#  makefile for formant @(#)Makefile	1.7 3/15/90 ESI
 	
formant:
	-emake -f xview.mk
	-emake -f sunview.mk

install:
	-emake -f xview.mk install
	-emake -f xview.mk clean
	-emake -f sunview.mk install

clean:
	-emake -f xview.mk clean
	-emake -f sunview.mk clean
