#  This material contains proprietary software of Entropic Speech, Inc.   
#  Any reproduction, distribution, or publication without the the prior	   
#  written permission of Entropic Speech, Inc. is strictly prohibited.
#  Any public distribution of copies of this work authorized in writing by
#  Entropic Speech, Inc. must bear the notice			
# 								
#      "Copyright (c) 1989 Entropic Speech, Inc.; All rights reserved"
# 				
#  makefile for cmap @(#)Makefile	1.4 9/9/91 ESI
 	

install: 
	emake -f xview.mk install
#	emake -f sunview.mk install

clean:
	rm -f *.o cmap xcmap
