# Filename is dc
label		: Laboratory Workbench (TM) MASSCOMP
instrument	: Untittled
save-state 	: 
module		: ESPS2LWB

records		: 0
scaling		: 0
sizes		: 1600,2,0
dimension	: 2
state		: 1
type		: 2
bufid		: 0
number		: 0
segment		: 0
time		: 0,0
# i.e., Wed Jan 20 13:05:10 1988
bufsize		: 0

x		: 0
gain		: 1
description	: Time
units		: seconds
slope		: 0.000125
conv gain	: 1
low limit	: 0
high limit	: 0.2
baseline	: 0

channel		: 0
gain		: 1
description	: channel 0
units		: volts
slope		: 1
conv gain	: 0.004883
low limit	: -10
high limit	: 10
baseline	: 0

channel		: 1
gain		: 1
description	: channel 1
units		: volts
slope		: 1
conv gain	: 0.004883
low limit	: -10
high limit	: 10
baseline	: 0

record:0 ascii_data:
