# Filename is dual_channel
label		: Laboratory Workbench (TM) MASSCOMP
instrument	: Saved_on_exit
save-state 	: .lwb_last
module		: lwb_out.15

records		: 0
scaling		: 0
sizes		: 1600,2,0
dimension	: 2
state		: 1
type		: 2
bufid		: 0
number		: 5
segment		: 0
time		: 541892405,66666
# i.e., Wed Mar  4 16.40.05 1987
bufsize		: 0
x		: 0
gain		: 1
description	: Time
units		: seconds
slope		: 0.000125
conv gain	: 1
low limit	: 0
high limit	: 0.2
baseline	: 0
channel		: 0
gain		: 1
description	: channel 0
units		: volts
slope		: 1
conv gain	: 0.00488281
low limit	: -10
high limit	: 10
baseline	: 0
channel		: 1
gain		: 1
description	: Channel 1
units		: Volts
slope		: 1
conv gain	: 0.00488281
low limit	: -10
high limit	: 10
baseline	: 0
record:0 offset:0 sizes:1600,2,0 number:1 segment:0 time:541892407,100000 ascii_data:
record:1 offset:15996 sizes:1600,2,0 number:1 segment:0 time:541892407,100000 ascii_data:
record:2 offset:31996 sizes:1600,2,0 number:1 segment:0 time:541892407,116666 ascii_data:
record:3 offset:47996 sizes:1600,2,0 number:1 segment:0 time:541892407,116666 ascii_data:
record:4 offset:63996 sizes:1600,2,0 number:1 segment:0 time:541892407,133333 ascii_data:
