.\" Copyright (c) 1987 Entropic Speech, Inc.; All rights reserved
.\" @(#)eman.1	3.6 7/6/92 ESI
.TH EMAN 1\-ESPS 7/6/92
.ds ]W (c) 1992 ERL, Inc.
.SH NAME
eman \- displays or prints ESPS manual pages
.SH SYNOPSIS
.B eman
[
.BI \-x " debug_level"
] [
.BI \-m " man page directory"
] [
.B \-t
] [
.I section
]
.I name
.br
.B eman
[
.BI \-x " debug_level"
] [
.BI \-m " man page directory"
]
.BI \-k " keyword"
.SH DESCRIPTION
.I Eman
is a
.IR man -like
program for examining the ESPS documentation. The main differences are that
a different directory tree is searched, and not all the features of the
Berkeley
.I man
program are implemented.
.PP
If no section number is given,
.I eman
searches the ESPS man directory tree for a file
.IP
man?/name.?
.PP
or
.IP
man?/name.?t
.PP
where the question marks are replaced with the same digit, the section number,
and the
.I t
suffix indicates that the file must be run through
.I tbl
before being formatted for viewing or printing.
Sections 1 through 8 are searched.
If
.I section
is given, it must be a digit from 1 to 8, and only that section is searched.
.PP
.I Eman
normalizes
.I name
by removing underscores
and truncating to a length of at most 10 characters
before searching for
.IP
man?/name.?
.PP
If no match is found, the program further truncates
.I name
to a maximum length of 9 before searching for
.IP
man?/name.?t
.PP
If still no match is found,
the program tries leaving the underscores in and just truncating as above,
both without the
.I t
suffix and with it.
.PP
If a match is found,
.I eman
looks for a preformatted version of the document, named
.IP
cat?/name.?
.PP
If the preformatted version is found
and is more recent than the source page,
a pager program is executed to print the formatted version.
This is the program, if any,
whose name is the value of the environment variable PAGER;
the default is
.I more.
If no preformatted version is found, a new one is generated.
.SH OPTIONS
.PP
The following options are supported.
.TP
.BI \-x " debug_level"
If
.I debug_level
is 1 or greater, debugging information is written to standard error.
.TP
.B \-m " man page directory"
The directory to look for the man pages.  This directory should contain
sub-directories \fIman1\fR, \fIman2\fR, etc., and \fIcat1\fR, \fIcat2\fR, etc.
By default \fIeman\fR looks in the directory specified for the manual
pages in the ESPS installation script.   This option is only needed to
override that.
.TP
.B \-t
The source for the manual page is formatted with
.I troff
and typeset.
.TP
.BI \-k " keyword"
The \fIwhatis\fR file in the ESPS man directory tree
is searched for entries that match
.I keyword.
.PP
The organization of sections is the same as for the Unix manual tree;
main programs are described in section 1; library routines are described
in section 3; data file formats are described in section 5; system maintenance
documents are in section 8. Other sections (for which the correspondence with
the Unix manual tree makes no sense) are reserved for future use.
.SH "SEE ALSO"
.PP
man(1), col(1), grep(1), more(1), nroff(1), troff(1), tbl(1)
.SH FILES
.nf
.ta 2.5i
man[1\-8]/*.[1\-8],
man[1\-8]/*.[1\-8]t	source files
cat[1\-8]/*.[1\-8]	preformatted pages
whatis	database for \-k option.
.SH DIAGNOSTICS
The user is informed if no document with the requested name can be found, or
if execution of the pager,
.I troff,
or
.I nroff
fails.
.SH AUTHOR
Joseph T. Buck.  Revisions by Ajaipal S. Virdy and Rodney W. Johnson.
