.\" Copyright (c) 1991 Entropic Research Laboratory, Inc.; All rights reserved
.\" @(#)nodiff.1	1.3 4/3/97 ERL
.ds ]W (c) 1991 Entropic Research Laboratory, Inc.
.TH  NODIFF 1\-ESPS 4/3/97
.SH NAME

.nf
nodiff \- nth order difference program
.fi
.SH SYNOPSIS
.B
nodiff [
.BI \-o " order"
] [
.BI \-f " field_name" 
] [
.BI \-r " range"
] [
.BI \-x " debug_level"
] fea.in fea.out
.PP
.SH DESCRIPTION
\fINodiff\fP
is a shell script which finds the nth-order difference of field
\fIfield_name\fP in the ESPS FEA (5\-ESPS) file \fIfea_in\fP and writes
the result to the output file \fIfea.out\fP.  The name of the field
in the output file is obtained by appending one of \fI_d1, ..., _d5\fP 
to \fIfield_name\fP, in agreement with \fIorder\fP.
.PP
The first order difference of \fIfield_name\fP is computed element\-
by\-element as \fIfield_name[i][recno] - field_name[i][recno-1]\fP
for all elements \fBi\fP of the field \fIfield_name\fP. The second
order difference is found as 
\fIfield_name[i][recno] -2 field_name[i][recno-1] 
+ field_name[i][recno-2]\fP.  
.PP
\fINodiff\fP uses \fItofeasd\fP (1\-ESPS) to translate the specified
field in the input file into a FEA_SD (5\-ESPS) file.  The output
of \fItofeasd\fP is piped to \fIfilter\fP (1\-ESPS), 
which uses predefined FEA_FILT (5\-ESPS) files to find the correct order difference.
\fIfeafunc\fP (1-ESPS) is used to give the filtered data the correct
field name, and 
\fImergefea\fP (1-ESPS) is used to combine the differenced data with the
original data to form the output records.
.PP
.SH OPTIONS
.PP
The following options are supported:
.TP
.BI \-o " order \fR[1]\fP"
determines which order difference to compute;
valid values are 1 through 5.  The FEAFILT files
\fIdiff1.filt\fP, ..., \fIdiff5.filt\fP contain the necessary
filter coefficients. They are found in the directory $ESPS_BASE/lib/filters.
.TP
.BI \-f " field_name \fR[spec_param]\fP"
name of the field whose difference is to be found.
.TP
.BI \-r " range \fR[1:last_in_file]\fP"
range of records to process.  Default is to process every record
in the input file.  The \fB\-r\fP option cannot be used
with standard input.
.TP
.BI \-x " debug_level \fR[0]\fP"
If 
.I debug_level
is positive,
debugging messages and other information are printed on the standard error
output.  The messages proliferate as the  
.I debug_level
increases.  If \fIdebug_level\fP is 0 (the default), no messages are
printed.  
.SH ESPS PARAMETERS
.PP
There is no paramter processing.
.SH ESPS COMMON
.PP
Common files are not used.
.SH ESPS HEADERS
.PP
All header information is copied from input to output. Additionally,
\fIfilter\fP (1-ESPS) adds information about the difference filter
used.
.SH BUGS
.PP
None known.
.SH "SEE ALSO"
copysps (1-ESPS), tofeasd (1-ESPS), filter (1-ESPS), 
.br
feafunc (1-ESPS), mergefea (1-ESPS), ESPS (5-ESPS), 
.br
FEA (5-ESPS), FEA_SD (5-ESPS)
.PP
.SH AUTHOR
.PP
Program and man page by Bill Byrne.




