.\" Copyright (c) 1992 Entropic Speech, Inc.; All rights reserved
.\" @(#)freewaves.1	1.4 9/26/97 ERL
.TH FREEWAVES 1\-ESPS 9/26/97
.ds ]W Entropic Research Lab, Inc.
.SH "NAME"
freewaves \- free a Waves+ License held by a lost Waves
.SH "SYNOPSIS"
.B freewaves
.SH "DESCRIPTION"
.PP
.I freewaves
.PP
releases a \fIwaves+\fR license if one is held by the user that runs
this program.  This is intended to be used to release a license that is
held by a zombied \fIwaves+\fR, or to release a stuck license if
\fIwaves+\fR exits abnormally.   While this program could be used to
release a license being held by a \fIwaves+\fR process while it is
running, if another \fIwaves+\fR is started that causes the number of
\fIwaves+\fR in use to exceed the total number of licenses, then one of
the \fIwaves+\fR will be terminated due to its losing its license.
.PP
Note that if a license is held by a zombied or dead process it is released by
the license manager within 60 seconds (at least that is the way the system 
is designed to work).
.SH "ESPS HEADERS"
.PP
This program ignores all header items.
.SH "ESPS PARAMETERS"
.PP
This program does not access the parameter file.
.SH OPTIONS
.PP
None.
.SH "SEE ALSO"
.PP
\fIelmd\fR(1\-ESPS), \fIelmadmin\fR(1\-ESPS)
