.\" Copyright (c) 1990 Entropic Speech, Inc.; All rights reserved
.\" @(#)emakecats.1	1.1 3/20/90 ESI
.TH EMAKECATS 1\-ESPS 3/20/90
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH NAME
emakecats \- make \fIcat\fP versions of ESPS manual pages
.SH SYNOPSIS
.B emakecats
.SH DESCRIPTION
.I Emakecats
makes the pre-stored nroff versions of the ESPS manual pages.
It makes them for sections 1, 3, and 5.
This make the manual pages come up fast
when \fIeman\fP (1\-\s-1ESPS\s+1) is used.
.SH "SEE ALSO"
.PP
\fIeman\fP (1\-\s-1ESPS\s+1), \fImakewhatis\fP (1\-\s-1ESPS\s+1)
.SH FILES
.nf
man1/*.1, 
man1/*.1t, 
man3/*.3, 
man3/*.3t, 
man5/*.5t
.fi
.SH DIAGNOSTICS
.SH AUTHOR

