.\" Copyright (c) 1990 Entropic Speech, Inc.; All rights reserved
.\" @(#)makewhatis.1	1.3 3/23/90 ESI
.TH MAKEWHATIS 1\-ESPS 3/23/90
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH NAME
makewhatis \- makes the whatis file for eman -k 
.SH SYNOPSIS
.B makewhatis
.SH DESCRIPTION
.I Makewhatis
makes the \fIwhatis\fP database file so that the \fB\-k\fP
option of \fIeman\fP (1\-\s-1ESPS\s+1)
works.
.SH "SEE ALSO"
.PP
\fIeman\fP (1\-\s-1ESPS\s+1), \fIemakecats\fP (1\-\s-1ESPS\s+1)
.SH FILES
.nf
man1/*.1, 
man1/*.1t, 
man3/*.3, 
man3/*.3t, 
man5/*.5t
.fi
.SH DIAGNOSTICS
.SH AUTHOR

