.\" Copyright (c) 1987 Entropic Speech, Inc.; All rights reserved
.\" @(#)dcopy.3	1.5 20 Oct 1987 ESI
.TH D_COPY 3\-ESPSu 20 Oct 1987
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH NAME
d_copy \- copy an array of double precision values
.SH SYNOPSIS
.ft B
d_copy(out,in,n)
.br
double *out,*in;
.br
int n;
.ft
.SH DESCRIPTION
.PP
.I D_copy
copies
.I n
double precision values from
.I in
to
.I out .
No checks are made.
.SH EXAMPLES

.SH DIAGNOSTICS

.SH AUTHOR
