.\" Copyright (c) 1987 Entropic Speech, Inc.; All rights reserved
.\" @(#)dmatfree.3	1.3 04 Jun 1987 ESI
.TH D_MAT_FREE 3\-ESPSu 04 Jun 1987
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH "NAME"
d_mat_free \- frees a pointer to a matrix of doubles
.SH "SYNOPSIS"
.B #include <stdio.h>
.br
.B d_mat_free (mat, nb_row)
.br
.B double **mat;
.br
.B int nb_row;
.SH "DESCRIPTION"
.PP
.I d_mat_free
frees a pointer to a matrix of doubles pointed to by
.I mat.
.SH "EXAMPLE"
.PP
int	row_size;	/* number of rows to free */
.br
double	**matrix;	/* two-dimensional array to free */
.br

(void) d_mat_free (matrix, row_size);
.br
.SH DIAGNOSTICS
.PP
None.
.SH "BUGS"
.PP
None Known.
.SH "AUTHOR"
.PP
Code by Bernard G. Fraenkel, Man page by Ajaipal S. Virdy.
