.\" Copyright (c) 1998 Entropic, Inc. All rights reserved.
.\" @(#)get_snr.3	1.1 9/4/98 ESI/ERL
.ds ]W (c) 1998 Entropic, Inc.
.TH GET_SNR 3\-ESPSsp 9/4/98
.SH NAME
get_snr \- Compute the signal-to-noise ratio between 2 data segments
.SH SYNOPSIS
.ft B
float 
.br
get_snr ( refData, procData, segmentSize )
.br
float   refData[], procData[];
.br
int     segmentSize;
.SH DESCRIPTION
This function takes 2 input data vectors and information about their
size and computes an SNR measurement by using the following formula:
.nf
\fB
     SNR = 10 * log10 { SUMn refData(n)^2 / SUMn {refData(n) \- procData(n)}^2 }
\fP                     
.fi
where \fIrefData(n)\fP is the reference data, \fIprocData(n)\fP 
is the processed data, and
\fISUMn\fP is the sum over all the input data elements (from 1 to 
\fIsegmentSize\fP).
.PP
\fIget_snr\fP handles the singular cases involving 0 in the following way:
.IP \ \ \(bu
if only the numerator is zero, the 10*log10{} result is 
set to -385.0
.IP \ \ \(bu
if only the denominator is zero, the 10*log10{} result is   
set to +385.0
.IP \ \ \(bu
if both numerator and denominator are zero, the 10*log10{} result 
is set to 0.0
.SH BUGS
None known.
.SH SEE ALSO
.nf

.fi
.SH REFERENCES
.HP
[1] S. Quackenbush, T. Barnwell, and M. Clements, 
.I Objective Measures of Speech Quality,
Prentice Hall, New Jersey, 1988, Chap. 2
.sp
.SH AUTHOR
David Burton
