.\" Copyright (c) 1987-1990 Entropic Speech, Inc.
.\" Copyright (c) 1997 Entropic Research Laboratory, Inc. All rights reserved.
.\" @(#)getsdtype.3	1.6 18 Apr 1997 ESI/ERL
.ds ]W (c) 1997 Entropic Research Laboratory, Inc.
.TH GET_SD_TYPE 3\-ESPSu 18 Apr 1997
.SH NAME
get_sd_type \- get the type of data in an ESPS sampled-data (FEA_SD or SD) file
.SH SYNOPSIS
.ft B
#include <esps/esps.h>
.br
int
.br
get_sd_type(hd)
.br
struct header *hd;
.ft
.SH DESCRIPTION
.I get_sd_type
returns the type of the data in the ESPS sampled-data (SD or FEA_SD) file
for which \fIhd\fR is a pointer to the header.
The type is one of the constants
DOUBLE, FLOAT, LONG, SHORT, CHAR, BYTE,
DOUBLE_CPLX, FLOAT_CPLX, LONG_CPLX, SHORT_CPLX, BYTE_CPLX.
These values are defined in
.I <esps/esps.h>.   
.SH DIAGNOSTICS
If \fIhd\fR does not point to the header of an SD or FEA_SD file,
an error message is printed and the program is terminated with exit status 1.
.SH BUGS
None known.
.SH SEE ALSO
.nf
ESPS(5\-ESPS), SD(5\-ESPS), \fIset_sd_type\fP(3\-ESPSu)
.fi
.SH AUTHOR
Alan Parker
