.\" Copyright (c) 1996 Entropic Research Laboratory, Inc.; All rights reserved
.\" @(#)decplay.1	@(#)decplay.1	1.1 11/21/96
.ds ]W (c) 1996 Entropic Research Laboratory, Inc.
.TH DECPLAY 1\-ESPS 
.SH NAME
decplay - send sampled data (PCM) to DEC Alpha audio device
.PP
.SH SYNOPSIS
.B decplay
[
.BI \-r " sample_range"
] [
.BI \-S " time_range"
] [ 
.I " file1"
[ 
.I " file2 ..."
] ]
.PP
.SH DESCRIPTION
.PP
.PP
\fIdecplay\fP sends all or a portion of one or more ESPS sampled data files (or files with ESPS default headers defined) to the audio device of a DEC Alpha.  
.PP
This program is for the DEC Alpha with multimedia extensions. To be
more precise, the DEC utility audioplay must exist, because
\fIdecplay\fP(1-ESPS) is simply a wrapper around it. The DEC
supplied audio capabilities are typically in /usr/bin/mme.
.PP
Use the DEC tool "audiocontrol" in the DEC multimedia extensions kit
to set the input and output controls (level, balance, port).  
.SH OPTIONS
.PP
The following options are supported:
.TP
.BI \-r " sample_range"
Select a subrange of points to be played, using the format
.I start:end 
or
.IR start:+count .
Either the start or the end may be omitted; the beginning or the end of the
file are used if no alternative is specified. To specify a range in
seconds, use \-S (see below) instead of \-r.  \-r may not be used with \-S.
.TP
.BI \-S " time_range"
Select a subrange of the file to be played, using the format
.I start_time:end_time
or
.I start_time:+time_incr.
Either the start or the end may be omitted; the beginning or the end of the
file are used if no alternative is specified. To specify a range in
seconds, use \-S (see below) instead of \-r.  \-r may not be used with \-S.
.IP
\-S is similar to \-r, except that the range limits are
interpreted as times (in seconds).  If start_time is omitted, it
is set to the value of the start_time generic header item.  If
end_time is omitted, it is set to the time corresponding to the end
of the file.  No more than one of the options \-r and \-S should be used.
.PP
.SH ESPS PARAMETERS
.PP
The parameter file is not read.  
.PP
.SH ESPS COMMON
.PP
ESPS Common processing may be disabled by setting the
environment variable USE_ESPS_COMMON to "off".  The default 
ESPS Common file is .espscom in the user's home directory.  See
\fIcopysd\fP(1\-\s-1ESPS\s+1) for further details.
.PP
.SH WARNINGS
.PP
decplay does not work if another process has control of the audio
device, such as DECsound (decsound) or the VU meter of Audio Control.
You will get the following errors
.nf
    
    audioplay: <error> Error opening Wave device
    audioplay: <error> Unsupported wave format
.if
.PP
Only a limited set of sample rates are available:
8000, 11025, 16000, 22050, 32000, 33075, 44100, and 48000.
Specifying a value other than one of these is an error.
.PP
.SH FILES
.PP
.SH BUGS
.PP
.PP
.SH SEE ALSO
.PP
\fIcopysd\fP(1\-\s-1ESPS\s+1), \fIdecrecord\fP (1\-\s-1ESPS\s+1), \fIsfconvert\fP (1\-\s-1ESPS\s+1)
.PP
.SH AUTHOR
.PP
Alan Parker, man page by Gayle Ayers Elam.
