#! /bin/sh
#@(#)get_demo	1.3 11/15/90
# Assume that you are standing in the "entropic" directory
# This only works for the SPARCstation or sun4 without audio

rsh masscomp fixowner burton erldemo

esccs erldemo get ENTROPIC; chmod 555 ENTROPIC
esccs erldemo get README;   chmod 444 README

#make script files
mkdir erldemos;chmod 755 erldemos
cd erldemos
esccs erldemo get attach.com; chmod 444 attach.com
esccs erldemo get cursors.com; chmod 444 cursors.com
esccs erldemo get intro.com; chmod 444 intro.com
esccs erldemo get shimmer.com; chmod 444 shimmer.com
esccs erldemo get single_demo.com; chmod 444 single_demo.com
esccs erldemo get waveforms.com; chmod 444 waveforms.com
esccs erldemo get windows.com; chmod 444 windows.com
esccs erldemo get xslideshow.sh; chmod 555 xslideshow.sh
esccs erldemo get wavesdemo.sh; chmod 555 wavesdemo.sh
esccs erldemo get erldemo.sh; chmod 555 erldemo.sh
esccs erldemo get one_demo.sh; chmod 555 one_demo.sh
esccs erldemo get edemo.about; chmod 444 edemo.about
esccs erldemo get edemo.info; chmod 444 edemo.info

#make audio files
mkdir audio; chmod 755 audio; 
cp $HOME/entropic/erldemos/audio/* audio; chmod 444 audio/*

#make files for displaying data 
mkdir files; chmod 755 files
cp $HOME/entropic/erldemos/files/* files; chmod 444 files/*

#make esps tree
mkdir esps;chmod 755 esps;cd esps

cp -r $HOME/entropic/erldemos/esps/bin bin; chmod 555 bin/*
cp -r $HOME/entropic/erldemos/esps/man man; 
chmod 755 man;cd man;chmod 755 man1; chmod 755 cat1;
chmod 444 whatis;chmod 444 man1/*;chmod 444 cat1/*
cd ..
cp -r $HOME/entropic/erldemos/esps/lib lib; 
chmod 755 lib;chmod 755 lib/waves;chmod 444 lib/waves/*
cp -r $HOME/entropic/erldemos/esps/32bin 32bin; chmod 555 32bin/*
cd ..

#make slides
mkdir snaps; chmod 755 snaps
cp $HOME/entropic/erldemos/snaps/eplots1 snaps; chmod 444 snaps/eplots1
cp $HOME/entropic/erldemos/snaps/images1 snaps; chmod 444 snaps/images1
cp $HOME/entropic/erldemos/snaps/ewave2 snaps; chmod 444 snaps/ewave2
cp $HOME/entropic/erldemos/snaps/filter1 snaps; chmod 444 snaps/filter1
cp $HOME/entropic/erldemos/snaps/eplots2 snaps; chmod 444 snaps/eplots2
cp $HOME/entropic/erldemos/snaps/ewave1 snaps; chmod 444 snaps/ewave1


#make play scripts
mkdir play_scripts; chmod 755 play_scripts; cd play_scripts
esccs erldemo get play.ext play.int play.none play.vme;chmod 555 play.*


cd ../..
echo " "
echo all done

