#
# This material contains unpublished, proprietary software of 
# Entropic Research Laboratory, Inc. Any reproduction, distribution, 
# or publication of this work must be authorized in writing by Entropic 
# Research Laboratory, Inc., and must bear the notice: 
#
#    "Copyright (c) 1987-1990  Entropic Speech, Inc. 
#    "Copyright (c) 1990-1996  Entropic Research Laboratory, Inc. 
#                   All rights reserved"
#
# The copyright notice above does not evidence any actual or intended 
# publication of this source code.     
#
# @(#)makefile	1.13	6/25/97	ESI/ERL
# 
# Written by:  
# Checked by:
# Revised by:
# 
# Makefile for:  lib_header (ESPS header.o library with license manager)
#


GFLAG = -g
CFLAGS =  $(GFLAG) $(CCKR) $(LIBCFLAGS)  $(OFLAGS) 
FFLAGS =  $(LIBFFLAGS)
ELMDIR = $(LIBDIR)/elm
OBJS = genhd.o eopen.o ss.o
SPHERE_LIBS = $(LIBDIR)/sphere
SPHERE_INC = sphere2.6/include

ESIGNAL_LIB = $(LIBDIR)
#ESIGNAL_LIB = esignal/lib
ESIGNAL_INC = esignal/src

install:	$(LIBDIR)/$(EHDRLIB) $(LIBDIR)/$(WHDRLIB) $(LIBDIR)/$(SHDRLIB) \
	$(LIBDIR)/$(NHDRLIB)


$(LIBDIR)/$(EHDRLIB):	 $(OBJS) esps/headers.o 
		mv headers.o foo.o
		ar rv $@  $?; $(RANLIB) $@
		mv foo.o headers.o

$(LIBDIR)/$(WHDRLIB):	 $(OBJS) waves/headers.o 
		mv headers.o foo.o
		ar rv $@  $?; $(RANLIB) $@
		mv foo.o headers.o

$(LIBDIR)/$(SHDRLIB):	 $(OBJS) ers/headers.o 
		mv headers.o foo.o
		ar rv $@  $?; $(RANLIB) $@
		mv foo.o headers.o

$(LIBDIR)/$(NHDRLIB):	 $(OBJS) nolic_headers.o  sphere.o esignal_fea.o
		ar rv $@  $? 
		$(RANLIB) $@

$(NHDRLIB):	 $(OBJS) nolic_headers.o  sphere.o esignal_fea.o
		ar rv $@  $? 
		$(RANLIB) $@


# 
#

nolic_headers.o: $(SINC)/header.h $(SINC)/esps.h headers.c
		$(CC) -c -o nolic_headers.o -DNO_LIC $(DFLAGS) $(CFLAGS) headers.c
		
		
	
esps/headers.o:  license.c headers.o $(SINC)/header.h  $(ELMDIR)/libelm.a \
			$(SINC)/esps.h $(ELMDIR)/elm.h  sphere.o \
			$(ESIGNAL_LIB)/libesignal.a esignal_fea.o
		$(ELM_CC) -c  $(CFLAGS)  -I$(ELMDIR)  -DESPS_PROG $(NO_LIC) license.c
		mv license.o esps
		ld -o esps/headers.o -r headers.o  esps/license.o \
		$(ELMDIR)/libelm.a  sphere.o \
		esignal_fea.o $(ESIGNAL_LIB)/libesignal.a \
		$(SPHERE_LIBS)/libsp.a  $(SPHERE_LIBS)/libutil.a 

waves/headers.o: license.c headers.o  $(SINC)/header.h  $(ELMDIR)/libelm.a \
			$(SINC)/esps.h $(ELMDIR)/elm.h  sphere.o \
			$(ESIGNAL_LIB)/libesignal.a esignal_fea.o
		$(ELM_CC) -c $(OFLAGS) $(CFLAGS) -I$(ELMDIR) -I$(XVIEW_INC) -DWAVES_PROG $(NO_LIC) license.c
		mv license.o waves
		ld -o waves/headers.o -r headers.o waves/license.o \
		$(ELMDIR)/libelm.a  sphere.o \
		esignal_fea.o $(ESIGNAL_LIB)/libesignal.a \
		$(SPHERE_LIBS)/libsp.a  $(SPHERE_LIBS)/libutil.a 

ers/headers.o: license.c headers.o  $(SINC)/header.h  $(ELMDIR)/libelm.a \
			$(SINC)/esps.h $(ELMDIR)/elm.h  sphere.o \
			$(ESIGNAL_LIB)/libesignal.a esignal_fea.o
		$(ELM_CC) -c $(CFLAGS) -I$(ELMDIR) -I$(XVIEW_INC) -DWAVES_PROG -DERS_PROG $(NO_LIC) license.c
		mv license.o ers
		ld -o ers/headers.o -r headers.o ers/license.o \
		$(ELMDIR)/libelm.a  sphere.o \
		esignal_fea.o $(ESIGNAL_LIB)/libesignal.a \
		$(SPHERE_LIBS)/libsp.a  $(SPHERE_LIBS)/libutil.a 

nolic/headers.o: license.c headers.o  $(SINC)/header.h  $(ELMDIR)/libelm.a \
			$(SINC)/esps.h $(ELMDIR)/elm.h  sphere.o \
			$(ESIGNAL_LIB)/libesignal.a esignal_fea.o
#		$(ELM_CC) -c $(CFLAGS) -I$(ELMDIR) -I$(XVIEW_INC) -DNO_LIC license.c
#		mv license.o nolic
#		ld -o nolic/headers.o -r headers.o nolic/license.o \
#		$(ELMDIR)/libelm.a  sphere.o \
#		esignal_fea.o $(ESIGNAL_LIB)/libesignal.a \
#		$(SPHERE_LIBS)/libsp.a  $(SPHERE_LIBS)/libutil.a 

headers.o:	$(SINC)/header.h $(SINC)/esps.h 
genhd.o:	$(SINC)/header.h  $(SINC)/esps.h
eopen.o:	$(SINC)/esps.h
ss.o:		$(SINC)/ss.h
sphere.o:	$(SINC)/esps.h 
		$(ANSI_CC) -c $(GFLAG) -DLIB -DSCCS -I$(SPSDIR)/include \
			-D$(MACH) -I$(SPHERE_INC)  sphere.c

esignal_fea.o:	$(SINC)/esps.h $(SINC)/fea.h $(ESIGNAL_INC)/esignal.h \
			$(SINC)/esignal_fea.h
		$(ANSI_CC)  -c $(CFLAGS) -D$(MACH) -I$(ESIGNAL_INC) \
			esignal_fea.c


clean:
		-rm $(OBJS) headers.o esps/*.o waves/*.o ers/*.o sphere.o \
			esignal_fea.o nolic_headers.o *.a 


