.\" Copyright (c) 1990 Entropic Speech, Inc.; All rights reserved
.\" @(#)eversion.1	1.4 1.4 ESI
.TH EVERSION 1\-ESPS 11/26/96
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH "NAME"
eversion \- get information about the current ESPS version
.SH "SYNOPSIS"
.B eversion 
[
.B \-c
]
.SH "DESCRIPTION"
.PP
.I Eversion
provides information about the installed versions of ESPS and 
\fIwaves\fP+.  
.PP
If no options are given when calling \fIeversion\fP it
prints on standard output the release number.
.SH OPTIONS
.PP
The following option is supported:
.TP
.B \-c
This option causes \fIeversion\fR to display the customer number.
.SH "ESPS HEADERS"
.PP
This program ignores all header items.
.SH "ESPS PARAMETERS"
.PP
This program does not access the parameter file.
.SH "BUGS"
.PP
None known.
.SH "SEE ALSO"
.PP
\fIeman\fP (1\-\s-1ESPS\s+1)
