.\" Copyright (c) 1987,1988,1989, 1990 Entropic Speech, Inc.; All rights reserved
.\" @(#)plotsd.1	1.1	9/19/97	ESI
.TH PLOTSD 1\-ESPS 9/19/97
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH NAME
plotsd \- plot real sampled data from single-channel FEA_SD files
.SH SYNOPSIS
.B plotsd
[
.BI \-{prs} " range"
] [
.BI \-t " text"
] . . .  [
.BI \-x " level"
] [
.BI \-y " range"
] [
.BI \-E " expansion"
]
.br
[
.BI \-M " maxpnts"
] [
.BI \-Y " range"
] [
.BI \-W " generic window system options"
]
.I file
.SH DESCRIPTION
.PP
.I Plotsd
plots a portion of an ESPS sampled data file
.I file.   
The file must be a single-channel file.  If the file is complex, only
the real part is plotted.  For multi-channel or complex files,
consider using \fIdemux\fP (1\-\s-1ESPS\s+1) together with
\fIplotsd\fP(1-ESPS), or \fIgenplot\fP (1\-\s-1ESPS\s+1), or \fIxwaves\fP(1-ESPS) to plot directly.
.PP
If
.I file
is "\-", the standard input is read.
.PP
The plot is displayed in an X window.  The display has three pull down
menus: \fBFile\fR, \fBViews\fR, and \fBHelp\fR.    The \fBFile\fR menu
has two items: \fBPrint\fR and \fBQuit\fR.   \fBPrint\fR selects a
dialog box that has controls to produce a PostScript output of the
plot.   The \fBQuit\fR item causes the program to exit.
.PP
The \fBViews\fR menu has selectors that enable or disable display of
the box around the plot, the horizontal grid, the vertical grid, any
text (usually the file name and date), and the tick marks on the
reticle.  This menu also has buttons to enable all of the above items,
to redraw the original plot, and to refresh the plot as it is currently
shown.
.PP
The \fBHelp\fR menu has two items: \fBon Plot Tool\fR and \fBAbout
Plot Tool\fR.   These display a help file and version information.
.PP
If the \fB\-p\fP option is omitted, then the \fIrange\fP is computed
from the parameter and common files; otherwise the entire contents
of 
.I file 
is used as the default range.  
.PP
.I Plotsd
finds the maximum and  minimum values in the specified range 
and computes appropriate scales for the 
.IR x -
and 
.IR y -axes.
These automatic values can be overriden by the 
.B \-y
or
.B \-Y 
options.  
.PP
When displayed on the screen (see EXAMPLES, below), the plots
will take a long time if every point is plotted.  For this reason, 
.I plotsd
plots a maximum of approximately 3000 points across the range 
specified by the user (intermediate points are skipped).  This behavior
can be changed by means of the 
.B \-M 
option. 
.PP
.I Plotsd
will run faster if the 
.B \-Y
option is used, especially in the case of large files.  
.SH OPTIONS
.PP
The following options are supported:
.TP
.BI \-p " first:last"
.TP
.BI \-p " first:+incr
.TP
.BI \-r " first:last"
.TP
.BI \-r " first:+incr
Determines the range of points to be plotted.  In the first form
(first:last), a pair of unsigned integers gives the first and last
points of the range.  If
.I first
is omitted, 1 is used.  If 
.I last 
is omitted, the last point in the file is used.  The second form
(first:+incr) is equivalent to the first with
.I "last = first + incr".  
The \fB-r\fP is a synonym for \fB-p\fP.  
.TP
.BI \-s " range"
Select a range of points to be plotted in seconds. For compatibility with
DSC LISTEN, the beginning of the file is 0.
.TP
.BI \-t " text"
A line of text to be printed below the plot.  
Up to ten
.B \-t
options may be specified; they are printed as text lines in order below the
plot.
.TP
.BI \-x " level"
If
.I level
is nonzero, debugging information is written to the standard error output.
Default is 0 (no debugging output).
.TP
.BI \-y " low:high"
Specifies approximate lower and upper limits for the 
.IR y -axis.
The values are adjusted by 
.I plotsd
in an attempt to make an esthetically pleasing plot.  
.TP
.BI \-E " expansion"
The range selected by the
.B \-p
option or by the parameter and common files is shown in a context
consisting of additional points at each end.
The selected range is expanded by a fraction given by the argument
.I expansion
plus an additional amount chosen to make the endpoints round numbers.
The expanded range is plotted, and the ends of the actually chosen range are
flagged with vertical lines labeled with the
.IR x- coordinate
values.
.TP
.BI \-M " maxpnts\fR [3000]\fP"
Specifies that 
.I plotsd
plot up to an approximate maximum of 
.I maxpnts 
points.  If the total number of points in the 
.I range
exceeds 
.I maxpnts,
points are skipped evenly throughout.
As a special case,
.I maxpnts
= 0 specifies that no points are to be skipped.
.TP
.BI \-Y " low:high"
Specifies exact lower and upper limits for the 
.IR y -axis.
.TP
.BI \-W
This option is followed by a character
string consisting of the generic window system options. For example, on a
system running X windows, to cause the plot to appear at a particular
screen location the following command could be used: 
.sp
.br
\fIplotsd -W "=300x250+50+200" file\fR.
.PP
If the file to be plotted contains data of a single value, then the
horizontal grid is suppressed.  Otherwise the horizontal plot tends to
get lost on top of a grid line.
.SH EXAMPLE
.IP
.BI "plotsd " "<options> <filename>"
.SH "ESPS PARAMETERS"
No ESPS parameter file is read.
.SH "ESPS COMMON"
The following items are read from the ESPS Common file.  The values for
start and nan are not used if a range is specified on the command line or
if the input file is not the same file identified in the
Common file by the "filename" symbol. 
.IP
.I "start - integer"
.IP
This is the starting point in the sampled data file to begin
plotting. If it is zero, the beginning of the file is used.
.sp
.I "nan - integer"
.IP
This is the number of points (starting at 
.IR start )
to plot.
If it is zero, the entire file is used as the default.  
.sp
.I "filename - string"
.IP
This is the name of the file to be displayed if \fIfile\fP is omitted
from the command line.
.PP
The following items are written into the ESPS Common file:
.IP
.I "start - integer"
.IP
The left point in the range selected.
.sp
.I "nan - integer"
.IP
The number of points in the selected range.
.sp
.I "beginplot - integer"
.IP
The origin of the graph
.RI ( x -coordinate).
.sp
.I "endplot - integer"
.IP
The end point of the graph
.RI ( x -coordinate).
.sp
.I "prog - string"
.IP
This is the name of the program (\fIplotsd\fP in this case).
.sp
.I "filename - string"
.IP
This is the name of the file to be displayed.
The program terminates if \fIfilename\fP does not exist when \fIfile\fP
is not specified on the command line.
.PP 
ESPS Common processing may be disabled by setting the environment variable
USE_ESPS_COMMON to "off".  The default ESPS Common file is .espscom 
in the user's home directory.  This may be overidden by setting
the environment variable ESPSCOM to the desired path.  User feedback of
Common processing is determined by the environment variable ESPS_VERBOSE,
with 0 causing no feedback and increasing levels causing increasingly
detailed feedback.  If ESPS_VERBOSE is not defined, a default value of 3 is
assumed.
.SH "ESPS HEADERS"
.PP
.I Plotsd
reads the following field from the SD file header:
.I common.type.
.SH DIAGNOSTICS
.PP
.I Plotsd
complains if there is no such file, if the file is not a sampled data
file, or if the file is a mutli-channel file.  
.SH WARNING
Discarding points when more than
.I maxpoints
points are to be plotted can produce misleading results.
In particular, aliasing is possible if the data has periodic components
with periods comparable to or less than the spacing between the selected
points.
.SH EXPECTED CHANGES
.PP
Many more options may be added.
.SH SEE ALSO
\fIdemux\fP (1\-\s-1ESPS\s+1), \fImlplot\fP (1\-\s-1ESPS\s+1),
\fIgenplot\fP (1\-\s-1ESPS\s+1), 
.br
\fIscatplot\fP (1\-\s-1ESPS\s+1),
\fIplotspec\fP (1\-\s-1ESPS\s+1), \fIaplot\fP (1\-\s-1ESPS\s+1),
.br
FEA_SD (5\-\s-1ESPS\s+1)
.SH AUTHOR
.PP
.nf
Joseph T. Buck, Entropic Speech, Inc.
Adapted from a program by Shankar Narayan.
Converted by Rod Johnson to read new ESPS format.
Modified for ESPS Common by Ajaipal S. Virdy.
Modified for \-y, \-Y, and \-M by John Shore.
Manual page revised by John Shore.
\-E options added by Rod Johnson.
.fi
