.\" Copyright 1987 Entropic Speech Inc., all rights reserved
.\" @(#)eparam.1	1.3 11/18/96 ESI
.TH EPARAM 1\-ESPS 11/18/96
.ds ]W "\fI\s+4\ze\h'0.05'e\s-4\v'-0.4m'\fP\(*p\v'0.4m'\ Entropic Speech, Inc.
.SH "NAME"
eparam \- run an ESPS program with parameter prompts
.SH "SYNOPSIS"
.B eparam
.I " program_name"
.I " program_options"
.SH "DESCRIPTION"
.PP
.I Eparam
runs the ESPS program
.I program_name
using a default parameter file for that program.  The user is prompted for
all parameter values.  Each prompt includes in brackets a default value.
After each prompt, the user may accept the default value by entering a
carriage return or may provide a new value followed by a carriage return.  
All 
.I program_options,
which should include any required file names, are passed directly on 
to
.I program_name.
.PP
.I Eparam
may be used with any ESPS program that processes a parameter file, 
i.e., with any ESPS program that has the \fB\-P\fP option.  For 
example, the effect of running
.nf

    %eparam refcof input.sd output.fana

is the same as the direct call

    %refcof -P \fIesps_params\fP/Prefcof input.sd output.fana

.fi
where
.I esps_params
is the directory containing the default parameter files, and 
where Prefcof is the name of the default parameter file for 
\fIrefcof\fP (1\-\s-1ESPS\s+1).  The directory 
.I esps_params
is chosen during ESPS installation and is known to
.I eparam.
.PP
If you use
.I eparam
with an ESPS program that does not process a parameter file, 
you will get a usage message issued by 
.I program_name.
.PP
Since the default parameter files read form standard input,
\fIeparam\fR cannot in a case where the called ESPS program will read
data from standard input (\fiIe.g.\fR the input file\-name is given as
"\-").   Output to standard output is not affected.
.SH "OPTIONS"
.PP
No options to 
.I eparam
are supported currently.  All 
.I program_options
are passed on to
.I program_name.
.SH ESPS PARAMETERS
.PP
The ESPS Parameter file is not processed by 
.I eparam.
It is processed by ESPS programs invoked by
.I eparam.
For details in each case, see the manual page for 
.I program_name.  
.SH "ESPS COMMON"
.PP
ESPS Common processing is temporarily disabled by 
.I eparam
while
.I program_name
is executed. 
.SH ESPS HEADERS
.PP
See the manual page for 
.I program_name
.SH "FUTURE CHANGES"
.PP
.SH "SEE ALSO"
.PP
In each case, see the manual page for 
.I program_name.  
.SH "BUGS"
.PP
.SH "FILES"
.PP
The default parameter files are located in the directory $ESPS_BASE/lib/params
Within this directory, the individual parameter files are named as
"P\fIprogram_name\fP".
.SH "REFERENCES"
.PP

.SH "AUTHOR"
.PP
manual page and program by John Shore

