#! /bin/sh
# @(#)testfile	3.1 10/13/87 ESI
# test script for randplay program
echo " "
echo generate comparisons of files within three groups - {1,2,3},
echo {4,5}, and {6,7,8}. All are in directory /usr/data and the
echo name of the play program is newplay
echo " "
echo output of randplay:
echo " "
randplay -d /usr/data -n newplay - << ZAP
1 2 3
#
4 5
#
6 7 8
ZAP
echo " "
